/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/chronicles/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Chronicles */
    get: operations["gm_ui_api_list_chronicles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/chronicles/{chronicle_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Chronicle */
    get: operations["gm_ui_api_get_chronicle"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/chronicles/{chronicle_id}/beats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Beats
     * @description The beats `audience` ("all", "table" or a player id) had seen up to t (default: the latest).
     */
    get: operations["gm_ui_api_list_beats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/chronicles/{chronicle_id}/lattice": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Lattice
     * @description The unfiltered lattice ("all", the GM's view) or one player's lattice at t (default: latest).
     */
    get: operations["gm_ui_lattice_api_get_lattice"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/chronicles/{chronicle_id}/hypotheses/{hypothesis_id}/expectations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Expectations
     * @description Per open step, the latest readout at or before t (default: the latest) about this hypothesis.
     */
    get: operations["gm_ui_lattice_api_list_expectations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ChronicleSummary */
    ChronicleSummary: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      /** Kind */
      kind: string;
      /** Beat Count */
      beat_count: number;
    };
    /** ChronicleDetail */
    ChronicleDetail: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      /** Kind */
      kind: string;
      /** Last T */
      last_t: number;
      /** Players */
      players: components["schemas"]["PlayerSummary"][];
    };
    /** PlayerSummary */
    PlayerSummary: {
      /** Id */
      id: number;
      /** Name */
      name: string;
    };
    /** BeatSummary */
    BeatSummary: {
      /** T */
      t: number;
      /** Pred */
      pred: string;
      /** Text */
      text: string;
      /** Source Kind */
      source_kind: string;
      /** Quarantined */
      quarantined: boolean;
    };
    /** BindingEntry */
    BindingEntry: {
      /** Role */
      role: string;
      /** Entity Id */
      entity_id: number | null;
      /** Entity Name */
      entity_name: string | null;
    };
    /** FilledStep */
    FilledStep: {
      /** Step Id */
      step_id: string;
      /** Beat Ts */
      beat_ts: number[];
    };
    /** LatticeHypothesisOut */
    LatticeHypothesisOut: {
      /** Id */
      id: number;
      /** Schema Slug */
      schema_slug: string;
      /** Schema Name */
      schema_name: string;
      /** Binding */
      binding: components["schemas"]["BindingEntry"][];
      /** Status */
      status: string;
      /** Weight */
      weight: number;
      /** Created At T */
      created_at_t: number;
      /** Status Changed At T */
      status_changed_at_t: number | null;
      /** Filled Steps */
      filled_steps: components["schemas"]["FilledStep"][];
      /** Open Steps */
      open_steps: string[];
      /** Refines */
      refines: number | null;
      /** Voiced */
      voiced: boolean;
    };
    /** LatticeOut */
    LatticeOut: {
      /** T */
      t: number;
      /** Hypotheses */
      hypotheses: components["schemas"]["LatticeHypothesisOut"][];
    };
    /** CandidateOut */
    CandidateOut: {
      /** Label */
      label: string;
      /** Text */
      text: string;
      /** P */
      p: number;
      /**
       * Null
       * @default false
       */
      null: boolean;
      /** Binding Delta */
      binding_delta?: {
        [key: string]: number;
      } | null;
    };
    /** ExpectationOut */
    ExpectationOut: {
      /** Step Id */
      step_id: string;
      /** Computed At T */
      computed_at_t: number;
      /** Question */
      question: string;
      /** Candidates */
      candidates: components["schemas"]["CandidateOut"][];
      /** Outside Mass */
      outside_mass: number;
      /** For Player */
      for_player: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  gm_ui_api_list_chronicles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChronicleSummary"][];
        };
      };
    };
  };
  gm_ui_api_get_chronicle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chronicle_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChronicleDetail"];
        };
      };
    };
  };
  gm_ui_api_list_beats: {
    parameters: {
      query?: {
        audience?: string;
        t?: number | null;
      };
      header?: never;
      path: {
        chronicle_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BeatSummary"][];
        };
      };
    };
  };
  gm_ui_lattice_api_get_lattice: {
    parameters: {
      query?: {
        audience?: string;
        t?: number | null;
      };
      header?: never;
      path: {
        chronicle_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LatticeOut"];
        };
      };
    };
  };
  gm_ui_lattice_api_list_expectations: {
    parameters: {
      query?: {
        t?: number | null;
      };
      header?: never;
      path: {
        chronicle_id: number;
        hypothesis_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExpectationOut"][];
        };
      };
    };
  };
}
