# Generated by Django 5.2.17 on 2026-10-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chronicle", "0005_entity_slug_entity_entity_slug_unique_per_chronicle"),
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hypothesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("binding", models.JSONField()),
                ("weight", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("live", "Live"),
                            ("complete", "Complete"),
                            ("refuted", "Refuted"),
                            ("pruned", "Pruned"),
                        ],
                        default="live",
                        max_length=20,
                    ),
                ),
                ("created_at_t", models.PositiveIntegerField()),
                (
                    "status_changed_at_t",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "chronicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hypotheses",
                        to="chronicle.chronicle",
                    ),
                ),
                (
                    "refines",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refinements",
                        to="matching.hypothesis",
                    ),
                ),
                (
                    "refuted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chronicle.beat",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="schemas.schema"),
                ),
                (
                    "voiced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chronicle.player",
                    ),
                ),
                (
                    "voiced_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chronicle.utterance",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "hypotheses",
            },
        ),
        migrations.CreateModel(
            name="StepFill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="chronicle.beat",
                    ),
                ),
                (
                    "hypothesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fills",
                        to="matching.hypothesis",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="schemas.step"),
                ),
            ],
        ),
    ]
