# Generated by Django 5.2.17 on 2026-10-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hypothesis",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="absorbed",
                to="matching.hypothesis",
            ),
        ),
        migrations.AlterField(
            model_name="hypothesis",
            name="status",
            field=models.CharField(
                choices=[
                    ("live", "Live"),
                    ("complete", "Complete"),
                    ("refuted", "Refuted"),
                    ("pruned", "Pruned"),
                    ("merged", "Merged"),
                ],
                default="live",
                max_length=20,
            ),
        ),
    ]
