# Generated by Django 5.2.17 on 2026-10-03 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chronicle", "0005_entity_slug_entity_entity_slug_unique_per_chronicle"),
        ("matching", "0002_hypothesis_merged_into_alter_hypothesis_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="hypothesis",
            name="for_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chronicle.player",
            ),
        ),
    ]
