# Generated by Django 5.2.17 on 2026-10-03 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chronicle", "0005_entity_slug_entity_entity_slug_unique_per_chronicle"),
        ("llm", "0001_initial"),
        ("matching", "0003_hypothesis_for_player"),
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_at_t", models.PositiveIntegerField()),
                ("question", models.TextField()),
                ("candidates", models.JSONField()),
                ("outside_mass", models.FloatField(default=0.0)),
                (
                    "for_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chronicle.player",
                    ),
                ),
                (
                    "hypothesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expectations",
                        to="matching.hypothesis",
                    ),
                ),
                (
                    "llm_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="llm.llmcall",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="schemas.step"),
                ),
            ],
        ),
    ]
