# Generated by Django 5.2.17 on 2026-10-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_hash", models.CharField(max_length=64, unique=True)),
                ("model", models.CharField(max_length=100)),
                ("endpoint", models.CharField(max_length=50)),
                ("request", models.JSONField()),
                ("response", models.JSONField()),
                ("server_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "LLM call",
            },
        ),
    ]
