# Generated by Django 5.2.17 on 2026-10-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmcall",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
