# Generated by Django 5.2.17 on 2026-10-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("roles", models.JSONField()),
                ("constraints", models.JSONField(blank=True, default=list)),
                ("payoff_steps", models.JSONField(blank=True, default=list)),
                ("prior", models.FloatField(default=0.0)),
                (
                    "origin",
                    models.CharField(
                        choices=[("library", "Library"), ("voiced", "Voiced")],
                        default="library",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_id", models.SlugField()),
                ("order", models.PositiveIntegerField()),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("development", "Development"),
                            ("payoff", "Payoff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("patterns", models.JSONField()),
                ("required", models.BooleanField(default=True)),
                ("repeatable", models.BooleanField(default=False)),
                ("weight", models.FloatField(default=1.0)),
                ("contradicts", models.JSONField(blank=True, default=list)),
                ("trigger", models.BooleanField(default=False)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="schemas.schema",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(fields=("schema", "step_id"), name="step_id_unique_per_schema")
                ],
            },
        ),
    ]
