# Generated by Django 5.2.17 on 2026-10-03 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chronicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("session", "Session"),
                            ("literature", "Literature"),
                            ("media", "Media"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["session", "literature", "media"])),
                        name="chronicle_kind_is_known",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("character", "Character"),
                            ("object", "Object"),
                            ("place", "Place"),
                            ("faction", "Faction"),
                            ("secret", "Secret"),
                            ("source", "Source"),
                        ],
                        max_length=20,
                    ),
                ),
                ("canonical_name", models.CharField(max_length=200)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("introduced_at_t", models.PositiveIntegerField()),
                (
                    "chronicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="chronicle.chronicle",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entities",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("implicit", models.BooleanField(default=False)),
                (
                    "chronicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="chronicle.chronicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utterance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("source", models.JSONField(blank=True, default=dict)),
                (
                    "chronicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utterances",
                        to="chronicle.chronicle",
                    ),
                ),
                (
                    "speaker_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chronicle.entity",
                    ),
                ),
                (
                    "speaker_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chronicle.player",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        ["character", "object", "place", "faction", "secret", "source"],
                    )
                ),
                name="entity_kind_is_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="utterance",
            constraint=models.UniqueConstraint(
                fields=("chronicle", "order"),
                name="utterance_order_unique_per_chronicle",
            ),
        ),
        migrations.AddConstraint(
            model_name="utterance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("speaker_player__isnull", True),
                    ("speaker_entity__isnull", True),
                    _connector="OR",
                ),
                name="utterance_has_at_most_one_speaker",
            ),
        ),
    ]
