# Generated by Django 5.2.17 on 2026-10-03 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chronicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t", models.PositiveIntegerField()),
                ("pred", models.CharField(max_length=50)),
                ("args", models.JSONField()),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("narration", "Narration"),
                            ("action", "Action"),
                            ("claim", "Claim"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=1.0)),
                ("original_pred", models.CharField(blank=True, max_length=50)),
                (
                    "chronicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beats",
                        to="chronicle.chronicle",
                    ),
                ),
                (
                    "source_utterance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beats",
                        to="chronicle.utterance",
                    ),
                ),
            ],
            options={
                "ordering": ["t"],
                "constraints": [
                    models.UniqueConstraint(fields=("chronicle", "t"), name="beat_t_unique_per_chronicle"),
                    models.CheckConstraint(
                        condition=models.Q(("source_kind__in", ["narration", "action", "claim"])),
                        name="beat_source_kind_is_known",
                    ),
                ],
            },
        ),
    ]
