# Generated by Django 5.2.17 on 2026-10-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chronicle", "0002_beat"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="chronicle.entity",
                    ),
                ),
                (
                    "source_beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="chronicle.beat",
                    ),
                ),
            ],
        ),
    ]
