# Generated by Django 5.2.17 on 2026-10-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chronicle", "0003_entityattribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopeGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t", models.PositiveIntegerField()),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="chronicle.beat",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge",
                        to="chronicle.entity",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge",
                        to="chronicle.player",
                    ),
                ),
                (
                    "via_beat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chronicle.beat",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("character__isnull", True), ("player__isnull", False)),
                            models.Q(("character__isnull", False), ("player__isnull", True)),
                            _connector="OR",
                        ),
                        name="scope_grant_names_exactly_one_subject",
                    )
                ],
            },
        ),
    ]
