# Generated by Django 5.2.17 on 2026-10-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chronicle", "0004_scopegrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug", ""), _negated=True),
                fields=("chronicle", "slug"),
                name="entity_slug_unique_per_chronicle",
            ),
        ),
    ]
