# Generated by Django 5.2.17 on 2026-10-04 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chronicle", "0005_entity_slug_entity_entity_slug_unique_per_chronicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("false", "False"),
                            ("unverified", "Unverified"),
                            ("misleading", "Misleading"),
                        ],
                        max_length=20,
                    ),
                ),
                ("labeler", models.CharField(max_length=200)),
                ("note", models.TextField(blank=True)),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_labels",
                        to="chronicle.beat",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("beat", "labeler"),
                        name="one_fact_label_per_labeler_and_beat",
                    )
                ],
            },
        ),
    ]
